twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        ga_tracking: 'UA-xxxxx-x'
        isHeaderTransparent: false
        upload_directory: '/uploads'

when@test:
    twig:
        strict_variables: true
